apiVersion: v1
kind: PersistentVolume
metadata:
  name: huggingface-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/d/hf
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - a3

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huggingface-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Should match or be less than the size specified in PV
  storageClassName: local-storage
