#storage.yml

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-output-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/brian/github/ComfyUI/output
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - a2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-output-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: comfyui-output-pv

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-models-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/brian/github/ComfyUI/models
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - a2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-models-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: comfyui-models-pv
